### ISSUE TITLE
ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path

### ISSUE THREAD

**Issue by renk100** [imuhao/RxPicker#8]
Android studio 3.0
jdk 1.8
phone: 小米3
Error：
 java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/bag.small-1.apk"],nativeLibraryDirectories=[/data/app-lib/bag.small-1, /vendor/lib, /system/lib]]
                                                               at android.app.ActivityThread.installProvider(ActivityThread.java:4790)
                                                               at android.app.ActivityThread.installContentProviders(ActivityThread.java:4382)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4322)
                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:138)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:136)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5016)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
                                                               at dalvik.system.NativeStart.main(Native Method)
                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/bag.small-1.apk"],nativeLibraryDirectories=[/data/app-lib/bag.small-1, /vendor/lib, /system/lib]]
                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                               at android.app.ActivityThread.installProvider(ActivityThread.java:4775)
                                                               at android.app.ActivityThread.installContentProviders(ActivityThread.java:4382) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4322) 
                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:138) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:136) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5016) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611) 
                                                               at dalvik.system.NativeStart.main(Native Method)

**Comment by imuhao** [comment]
你可以试下 clear 一下项目,然后重新构建运行项目.

**Comment by renk100** [comment]
clean，还是一样出错。在高版本，比如6.0手机，运行没问题。
