### ISSUE TITLE
在子进程中报错

### ISSUE THREAD

**Issue by tangchuanyong** [imuhao/RxPicker#9]
主进程没有问题，但是在子进程中。运行报错
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.caimuhao.rxpicker.utils.PickerConfig.isSingle()' on a null object reference
                                                                                     at com.caimuhao.rxpicker.ui.fragment.PickerFragment.initView(PickerFragment.java:98)
                                                                                     at com.caimuhao.rxpicker.base.AbstractFragment.onCreateView(AbstractFragment.java:31)
                                                                                     at android.app.Fragment.performCreateView(Fragment.java:2236)
                                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:978)
                                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
                                                                                     at android.app.BackStackRecord.run(BackStackRecord.java:800)
                                                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1562)
                                                                                     at android.app.FragmentController.execPendingActions(FragmentController.java:325)
                                                                                     at android.app.Activity.performStart(Activity.java:6324)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2540)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665) 
                                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                     at android.os.Looper.loop(Looper.java:207) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5765) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by tangchuanyong** [comment]
处理方法就是在清单文件为 <activity
        android:name=".ui.RxPickerActivity"
        android:launchMode="singleTop"
        android:screenOrientation="nosensor"
        android:theme="@style/RxPicker.AppTheme"
        android:multiprocess="true"/>

    <activity
        android:name=".ui.PreviewActivity"
        android:launchMode="singleTop"
        android:screenOrientation="nosensor"
        android:theme="@style/RxPicker.AppTheme"
        android:multiprocess="true"/>
加上多进程支持。就可以了

**Comment by imuhao** [comment]
好的
